// This file centralizes the definition of all available tools, organized by category.
export const categories = [
  {
    name: 'Popular Tools',
    tools: [
      {
        id: 'pdf-multi-tool',
        href: import.meta.env.BASE_URL + 'pdf-multi-tool.html',
        name: 'PDF Multi Tool',
        icon: 'ph-pencil-ruler',
        subtitle:
          'Merge, Split, Organize, Delete, Rotate, Add Blank Pages, Extract and Duplicate in an unified interface.',
      },
      {
        id: 'merge-pdf',
        href: import.meta.env.BASE_URL + 'merge-pdf.html',
        name: 'Merge PDF',
        icon: 'ph-browsers',
        subtitle: 'Combine multiple PDFs into one file. Preserves Bookmarks.',
      },
      {
        id: 'split-pdf',
        href: import.meta.env.BASE_URL + 'split-pdf.html',
        name: 'Split PDF',
        icon: 'ph-scissors',
        subtitle: 'Extract a range of pages into a new PDF.',
      },
      {
        id: 'compress-pdf',
        href: import.meta.env.BASE_URL + 'compress-pdf.html',
        name: 'Compress PDF',
        icon: 'ph-lightning',
        subtitle: 'Reduce the file size of your PDF.',
      },
      {
        id: 'edit-pdf',
        href: import.meta.env.BASE_URL + 'edit-pdf.html',
        name: 'PDF Editor',
        icon: 'ph-pencil-simple',
        subtitle:
          'Annotate, highlight, redact, comment, add shapes/images, search, and view PDFs',
      },
      {
        id: 'jpg-to-pdf',
        href: import.meta.env.BASE_URL + 'jpg-to-pdf.html',
        name: 'JPG to PDF',
        icon: 'ph-file-jpg',
        subtitle: 'Create a PDF from one or more JPG images.',
      },
      {
        id: 'sign-pdf',
        href: import.meta.env.BASE_URL + 'sign-pdf.html',
        name: 'Sign PDF',
        icon: 'ph-pen-nib',
        subtitle: 'Draw, type, or upload your signature.',
      },
      {
        id: 'crop-pdf',
        href: import.meta.env.BASE_URL + 'crop-pdf.html',
        name: 'Crop PDF',
        icon: 'ph-crop',
        subtitle: 'Trim the margins of every page in your PDF.',
      },
      {
        id: 'extract-pages',
        href: import.meta.env.BASE_URL + 'extract-pages.html',
        name: 'Extract Pages',
        icon: 'ph-squares-four',
        subtitle: 'Save a selection of pages as new files.',
      },
      {
        id: 'organize-pdf',
        href: import.meta.env.BASE_URL + 'organize-pdf.html',
        name: 'Duplicate & Organize',
        icon: 'ph-files',
        subtitle: 'Duplicate, reorder, and delete pages.',
      },
      {
        id: 'delete-pages',
        href: import.meta.env.BASE_URL + 'delete-pages.html',
        name: 'Delete Pages',
        icon: 'ph-trash',
        subtitle: 'Remove specific pages from your document.',
      },
    ],
  },
  {
    name: 'Edit & Annotate',
    tools: [
      {
        id: 'edit-pdf',
        href: import.meta.env.BASE_URL + 'edit-pdf.html',
        name: 'PDF Editor',
        icon: 'ph-pencil-simple',
        subtitle:
          'Annotate, highlight, redact, comment, add shapes/images, search, and view PDFs.',
      },
      {
        id: 'bookmark',
        href: import.meta.env.BASE_URL + 'bookmark.html',
        name: 'Edit Bookmarks',
        icon: 'ph-bookmark',
        subtitle: 'Add, edit, import, delete and extract PDF bookmarks.',
      },
      {
        id: 'table-of-contents',
        href: import.meta.env.BASE_URL + 'table-of-contents.html',
        name: 'Table of Contents',
        icon: 'ph-list',
        subtitle: 'Generate a table of contents page from PDF bookmarks.',
      },
      {
        id: 'page-numbers',
        href: import.meta.env.BASE_URL + 'page-numbers.html',
        name: 'Page Numbers',
        icon: 'ph-list-numbers',
        subtitle: 'Insert page numbers into your document.',
      },
      {
        id: 'add-watermark',
        href: import.meta.env.BASE_URL + 'add-watermark.html',
        name: 'Add Watermark',
        icon: 'ph-drop',
        subtitle: 'Stamp text or an image over your PDF pages.',
      },
      {
        id: 'header-footer',
        href: import.meta.env.BASE_URL + 'header-footer.html',
        name: 'Header & Footer',
        icon: 'ph-paragraph',
        subtitle: 'Add text to the top and bottom of pages.',
      },
      {
        id: 'invert-colors',
        href: import.meta.env.BASE_URL + 'invert-colors.html',
        name: 'Invert Colors',
        icon: 'ph-circle-half',
        subtitle: 'Create a "dark mode" version of your PDF.',
      },
      {
        id: 'background-color',
        href: import.meta.env.BASE_URL + 'background-color.html',
        name: 'Background Color',
        icon: 'ph-palette',
        subtitle: 'Change the background color of your PDF.',
      },
      {
        id: 'text-color',
        href: import.meta.env.BASE_URL + 'text-color.html',
        name: 'Change Text Color',
        icon: 'ph-eyedropper',
        subtitle: 'Change the color of text in your PDF.',
      },
      {
        id: 'sign-pdf',
        href: import.meta.env.BASE_URL + 'sign-pdf.html',
        name: 'Sign PDF',
        icon: 'ph-pen-nib',
        subtitle: 'Draw, type, or upload your signature.',
      },
      {
        id: 'add-stamps',
        href: import.meta.env.BASE_URL + 'add-stamps.html',
        name: 'Add Stamps',
        icon: 'ph-stamp',
        subtitle: 'Add image stamps to your PDF using the annotation toolbar.',
      },
      {
        id: 'remove-annotations',
        href: import.meta.env.BASE_URL + 'remove-annotations.html',
        name: 'Remove Annotations',
        icon: 'ph-eraser',
        subtitle: 'Strip comments, highlights, and links.',
      },
      {
        id: 'crop-pdf',
        href: import.meta.env.BASE_URL + 'crop-pdf.html',
        name: 'Crop PDF',
        icon: 'ph-crop',
        subtitle: 'Trim the margins of every page in your PDF.',
      },
      {
        id: 'form-filler',
        href: import.meta.env.BASE_URL + 'form-filler.html',
        name: 'PDF Form Filler',
        icon: 'ph-pencil-line',
        subtitle:
          'Fill in forms directly in the browser. Also supports XFA forms.',
      },
      {
        id: 'form-creator',
        href: import.meta.env.BASE_URL + 'form-creator.html',
        name: 'Create PDF Form',
        icon: 'ph-file-plus',
        subtitle: 'Create fillable PDF forms with drag-and-drop text fields.',
      },
      {
        id: 'remove-blank-pages',
        href: import.meta.env.BASE_URL + 'remove-blank-pages.html',
        name: 'Remove Blank Pages',
        icon: 'ph-file-minus',
        subtitle: 'Automatically detect and delete blank pages.',
      },
    ],
  },
  {
    name: 'Convert to PDF',
    tools: [
      {
        id: 'image-to-pdf',
        href: import.meta.env.BASE_URL + 'image-to-pdf.html',
        name: 'Images to PDF',
        icon: 'ph-images',
        subtitle:
          'Convert JPG, PNG, BMP, GIF, TIFF, PNM, PGM, PBM, PPM, PAM, JXR, JPX, JP2, PSD, SVG, HEIC, WebP to PDF.',
      },
      {
        id: 'jpg-to-pdf',
        href: import.meta.env.BASE_URL + 'jpg-to-pdf.html',
        name: 'JPG to PDF',
        icon: 'ph-file-jpg',
        subtitle: 'Create a PDF from one or more JPG images.',
      },
      {
        id: 'png-to-pdf',
        href: import.meta.env.BASE_URL + 'png-to-pdf.html',
        name: 'PNG to PDF',
        icon: 'ph-file-png',
        subtitle: 'Create a PDF from one or more PNG images.',
      },
      {
        id: 'webp-to-pdf',
        href: import.meta.env.BASE_URL + 'webp-to-pdf.html',
        name: 'WebP to PDF',
        icon: 'ph-image',
        subtitle: 'Create a PDF from one or more WebP images.',
      },
      {
        id: 'svg-to-pdf',
        href: import.meta.env.BASE_URL + 'svg-to-pdf.html',
        name: 'SVG to PDF',
        icon: 'ph-file-svg',
        subtitle: 'Create a PDF from one or more SVG images.',
      },
      {
        id: 'bmp-to-pdf',
        href: import.meta.env.BASE_URL + 'bmp-to-pdf.html',
        name: 'BMP to PDF',
        icon: 'ph-image',
        subtitle: 'Create a PDF from one or more BMP images.',
      },
      {
        id: 'heic-to-pdf',
        href: import.meta.env.BASE_URL + 'heic-to-pdf.html',
        name: 'HEIC to PDF',
        icon: 'ph-device-mobile',
        subtitle: 'Create a PDF from one or more HEIC images.',
      },
      {
        id: 'tiff-to-pdf',
        href: import.meta.env.BASE_URL + 'tiff-to-pdf.html',
        name: 'TIFF to PDF',
        icon: 'ph-image',
        subtitle: 'Create a PDF from one or more TIFF images.',
      },
      {
        id: 'txt-to-pdf',
        href: import.meta.env.BASE_URL + 'txt-to-pdf.html',
        name: 'Text to PDF',
        icon: 'ph-text-t',
        subtitle: 'Convert a plain text file into a PDF.',
      },
      {
        id: 'markdown-to-pdf',
        href: import.meta.env.BASE_URL + 'markdown-to-pdf.html',
        name: 'Markdown to PDF',
        icon: 'ph-markdown-logo',
        subtitle:
          'Convert Markdown to PDF with live preview and syntax highlighting.',
      },
      {
        id: 'json-to-pdf',
        href: import.meta.env.BASE_URL + 'json-to-pdf.html',
        name: 'JSON to PDF',
        icon: 'ph-file-code',
        subtitle: 'Convert JSON files to PDF format.',
      },
      {
        id: 'odt-to-pdf',
        href: import.meta.env.BASE_URL + 'odt-to-pdf.html',
        name: 'ODT to PDF',
        icon: 'ph-file',
        subtitle: 'Convert ODT (OpenDocument Text) files to PDF.',
      },
      {
        id: 'csv-to-pdf',
        href: import.meta.env.BASE_URL + 'csv-to-pdf.html',
        name: 'CSV to PDF',
        icon: 'ph-file-csv',
        subtitle: 'Convert CSV (Comma-Separated Values) spreadsheets to PDF.',
      },
      {
        id: 'rtf-to-pdf',
        href: import.meta.env.BASE_URL + 'rtf-to-pdf.html',
        name: 'RTF to PDF',
        icon: 'ph-file-text',
        subtitle: 'Convert RTF (Rich Text Format) documents to PDF.',
      },
      {
        id: 'word-to-pdf',
        href: import.meta.env.BASE_URL + 'word-to-pdf.html',
        name: 'Word to PDF',
        icon: 'ph-microsoft-word-logo',
        subtitle: 'Convert Word documents (DOCX, DOC, ODT) to PDF.',
      },
      {
        id: 'excel-to-pdf',
        href: import.meta.env.BASE_URL + 'excel-to-pdf.html',
        name: 'Excel to PDF',
        icon: 'ph-microsoft-excel-logo',
        subtitle: 'Convert Excel spreadsheets (XLSX, XLS, ODS) to PDF.',
      },
      {
        id: 'powerpoint-to-pdf',
        href: import.meta.env.BASE_URL + 'powerpoint-to-pdf.html',
        name: 'PowerPoint to PDF',
        icon: 'ph-microsoft-powerpoint-logo',
        subtitle: 'Convert PowerPoint presentations (PPTX, PPT, ODP) to PDF.',
      },
      {
        id: 'xps-to-pdf',
        href: import.meta.env.BASE_URL + 'xps-to-pdf.html',
        name: 'XPS to PDF',
        icon: 'ph-scan',
        subtitle: 'Convert XPS/OXPS documents to PDF.',
      },
      {
        id: 'mobi-to-pdf',
        href: import.meta.env.BASE_URL + 'mobi-to-pdf.html',
        name: 'MOBI to PDF',
        icon: 'ph-book-open-text',
        subtitle: 'Convert MOBI e-books to PDF.',
      },
      {
        id: 'epub-to-pdf',
        href: import.meta.env.BASE_URL + 'epub-to-pdf.html',
        name: 'EPUB to PDF',
        icon: 'ph-book-open-text',
        subtitle: 'Convert EPUB e-books to PDF.',
      },
      {
        id: 'fb2-to-pdf',
        href: import.meta.env.BASE_URL + 'fb2-to-pdf.html',
        name: 'FB2 to PDF',
        icon: 'ph-book-bookmark',
        subtitle: 'Convert FictionBook (FB2) e-books to PDF.',
      },
      {
        id: 'cbz-to-pdf',
        href: import.meta.env.BASE_URL + 'cbz-to-pdf.html',
        name: 'CBZ to PDF',
        icon: 'ph-book-open',
        subtitle: 'Convert comic book archives (CBZ/CBR) to PDF.',
      },
      {
        id: 'wpd-to-pdf',
        href: import.meta.env.BASE_URL + 'wpd-to-pdf.html',
        name: 'WPD to PDF',
        icon: 'ph-file-text',
        subtitle: 'Convert WordPerfect documents (WPD) to PDF.',
      },
      {
        id: 'wps-to-pdf',
        href: import.meta.env.BASE_URL + 'wps-to-pdf.html',
        name: 'WPS to PDF',
        icon: 'ph-file-text',
        subtitle: 'Convert WPS Office documents to PDF.',
      },
      {
        id: 'xml-to-pdf',
        href: import.meta.env.BASE_URL + 'xml-to-pdf.html',
        name: 'XML to PDF',
        icon: 'ph-file-code',
        subtitle: 'Convert XML documents to PDF.',
      },
      {
        id: 'pages-to-pdf',
        href: import.meta.env.BASE_URL + 'pages-to-pdf.html',
        name: 'Pages to PDF',
        icon: 'ph-file-text',
        subtitle: 'Convert Apple Pages documents to PDF.',
      },
      {
        id: 'odg-to-pdf',
        href: import.meta.env.BASE_URL + 'odg-to-pdf.html',
        name: 'ODG to PDF',
        icon: 'ph-image',
        subtitle: 'Convert OpenDocument Graphics (ODG) to PDF.',
      },
      {
        id: 'ods-to-pdf',
        href: import.meta.env.BASE_URL + 'ods-to-pdf.html',
        name: 'ODS to PDF',
        icon: 'ph-table',
        subtitle: 'Convert OpenDocument Spreadsheet (ODS) to PDF.',
      },
      {
        id: 'odp-to-pdf',
        href: import.meta.env.BASE_URL + 'odp-to-pdf.html',
        name: 'ODP to PDF',
        icon: 'ph-presentation',
        subtitle: 'Convert OpenDocument Presentation (ODP) to PDF.',
      },
      {
        id: 'pub-to-pdf',
        href: import.meta.env.BASE_URL + 'pub-to-pdf.html',
        name: 'PUB to PDF',
        icon: 'ph-book-open',
        subtitle: 'Convert Microsoft Publisher (PUB) to PDF.',
      },
      {
        id: 'vsd-to-pdf',
        href: import.meta.env.BASE_URL + 'vsd-to-pdf.html',
        name: 'VSD to PDF',
        icon: 'ph-git-branch',
        subtitle: 'Convert Microsoft Visio (VSD, VSDX) to PDF.',
      },
      {
        id: 'psd-to-pdf',
        href: import.meta.env.BASE_URL + 'psd-to-pdf.html',
        name: 'PSD to PDF',
        icon: 'ph-image',
        subtitle:
          'Convert Adobe Photoshop (PSD) files to PDF. Multiple files supported.',
      },
      {
        id: 'email-to-pdf',
        href: import.meta.env.BASE_URL + 'email-to-pdf.html',
        name: 'Email to PDF',
        icon: 'ph-envelope',
        subtitle: 'Convert email files (EML, MSG) to PDF format.',
      },
    ],
  },
  {
    name: 'Convert from PDF',
    tools: [
      {
        id: 'pdf-to-jpg',
        href: import.meta.env.BASE_URL + 'pdf-to-jpg.html',
        name: 'PDF to JPG',
        icon: 'ph-file-image',
        subtitle: 'Convert each PDF page into a JPG image.',
      },
      {
        id: 'pdf-to-png',
        href: import.meta.env.BASE_URL + 'pdf-to-png.html',
        name: 'PDF to PNG',
        icon: 'ph-file-image',
        subtitle: 'Convert each PDF page into a PNG image.',
      },
      {
        id: 'pdf-to-webp',
        href: import.meta.env.BASE_URL + 'pdf-to-webp.html',
        name: 'PDF to WebP',
        icon: 'ph-file-image',
        subtitle: 'Convert each PDF page into a WebP image.',
      },
      {
        id: 'pdf-to-bmp',
        href: import.meta.env.BASE_URL + 'pdf-to-bmp.html',
        name: 'PDF to BMP',
        icon: 'ph-file-image',
        subtitle: 'Convert each PDF page into a BMP image.',
      },
      {
        id: 'pdf-to-tiff',
        href: import.meta.env.BASE_URL + 'pdf-to-tiff.html',
        name: 'PDF to TIFF',
        icon: 'ph-file-image',
        subtitle: 'Convert each PDF page into a TIFF image.',
      },
      {
        id: 'pdf-to-svg',
        href: import.meta.env.BASE_URL + 'pdf-to-svg.html',
        name: 'PDF to SVG',
        icon: 'ph-file-code',
        subtitle: 'Convert each PDF page into a scalable vector graphic.',
      },
      {
        id: 'pdf-to-csv',
        href: import.meta.env.BASE_URL + 'pdf-to-csv.html',
        name: 'PDF to CSV',
        icon: 'ph-file-csv',
        subtitle: 'Extract tables from PDF and convert to CSV format.',
      },
      {
        id: 'pdf-to-excel',
        href: import.meta.env.BASE_URL + 'pdf-to-excel.html',
        name: 'PDF to Excel',
        icon: 'ph-microsoft-excel-logo',
        subtitle: 'Extract tables from PDF and convert to Excel (XLSX).',
      },
      {
        id: 'pdf-to-greyscale',
        href: import.meta.env.BASE_URL + 'pdf-to-greyscale.html',
        name: 'PDF to Greyscale',
        icon: 'ph-palette',
        subtitle: 'Convert all colors to black and white.',
      },
      {
        id: 'pdf-to-json',
        href: import.meta.env.BASE_URL + 'pdf-to-json.html',
        name: 'PDF to JSON',
        icon: 'ph-file-code',
        subtitle: 'Convert PDF files to JSON format.',
      },
      {
        id: 'pdf-to-docx',
        href: import.meta.env.BASE_URL + 'pdf-to-docx.html',
        name: 'PDF to Word',
        icon: 'ph-microsoft-word-logo',
        subtitle: 'Convert PDF files to editable Word documents.',
      },
      {
        id: 'extract-images',
        href: import.meta.env.BASE_URL + 'extract-images.html',
        name: 'Extract Images',
        icon: 'ph-download-simple',
        subtitle: 'Extract all embedded images from your PDF files.',
      },
      {
        id: 'pdf-to-markdown',
        href: import.meta.env.BASE_URL + 'pdf-to-markdown.html',
        name: 'PDF to Markdown',
        icon: 'ph-markdown-logo',
        subtitle: 'Convert PDF text and tables to Markdown format.',
      },
      {
        id: 'prepare-pdf-for-ai',
        href: import.meta.env.BASE_URL + 'prepare-pdf-for-ai.html',
        name: 'Prepare PDF for AI',
        icon: 'ph-sparkle',
        subtitle:
          'Extract PDF content as LlamaIndex JSON for RAG/LLM pipelines.',
      },
      {
        id: 'pdf-to-text',
        href: import.meta.env.BASE_URL + 'pdf-to-text.html',
        name: 'PDF to Text',
        icon: 'ph-text-aa',
        subtitle: 'Extract text from PDF files and save as plain text (.txt).',
      },
    ],
  },
  {
    name: 'Organize & Manage',
    tools: [
      {
        id: 'ocr-pdf',
        href: import.meta.env.BASE_URL + 'ocr-pdf.html',
        name: 'OCR PDF',
        icon: 'ph-barcode',
        subtitle: 'Make a PDF searchable and copyable.',
      },
      {
        id: 'merge-pdf',
        href: import.meta.env.BASE_URL + 'merge-pdf.html',
        name: 'Merge PDF',
        icon: 'ph-browsers',
        subtitle: 'Combine multiple PDFs into one file.',
      },
      {
        id: 'alternate-merge',
        href: import.meta.env.BASE_URL + 'alternate-merge.html',
        name: 'Alternate & Mix Pages',
        icon: 'ph-shuffle',
        subtitle:
          'Merge PDFs by alternating pages from each PDF. Preserves Bookmarks',
      },
      {
        id: 'organize-pdf',
        href: import.meta.env.BASE_URL + 'organize-pdf.html',
        name: 'Organize & Duplicate',
        icon: 'ph-files',
        subtitle: 'Duplicate, reorder, and delete pages.',
      },
      {
        id: 'add-attachments',
        href: import.meta.env.BASE_URL + 'add-attachments.html',
        name: 'Add Attachments',
        icon: 'ph-paperclip',
        subtitle: 'Embed one or more files into your PDF.',
      },
      {
        id: 'extract-attachments',
        href: import.meta.env.BASE_URL + 'extract-attachments.html',
        name: 'Extract Attachments',
        icon: 'ph-download',
        subtitle: 'Extract all embedded files from PDF(s) as a ZIP.',
      },
      {
        id: 'edit-attachments',
        href: import.meta.env.BASE_URL + 'edit-attachments.html',
        name: 'Edit Attachments',
        icon: 'ph-paperclip-horizontal',
        subtitle: 'View or remove attachments in your PDF.',
      },
      {
        id: 'pdf-multi-tool',
        href: import.meta.env.BASE_URL + 'pdf-multi-tool.html',
        name: 'PDF Multi Tool',
        icon: 'ph-pencil-ruler',
        subtitle: 'Full-featured PDF editor with page management.',
      },
      {
        id: 'pdf-layers',
        href: import.meta.env.BASE_URL + 'pdf-layers.html',
        name: 'PDF OCG',
        icon: 'ph-stack-simple',
        subtitle: 'View, toggle, add, and delete OCG layers in your PDF.',
      },
      {
        id: 'extract-tables',
        href: import.meta.env.BASE_URL + 'extract-tables.html',
        name: 'Extract Tables',
        icon: 'ph-table',
        subtitle: 'Extract tables from PDFs as CSV, JSON, or Markdown.',
      },
      {
        id: 'split-pdf',
        href: import.meta.env.BASE_URL + 'split-pdf.html',
        name: 'Split PDF',
        icon: 'ph-scissors',
        subtitle: 'Extract a range of pages into a new PDF.',
      },
      {
        id: 'divide-pages',
        href: import.meta.env.BASE_URL + 'divide-pages.html',
        name: 'Divide Pages',
        icon: 'ph-columns',
        subtitle: 'Divide pages horizontally or vertically.',
      },
      {
        id: 'extract-pages',
        href: import.meta.env.BASE_URL + 'extract-pages.html',
        name: 'Extract Pages',
        icon: 'ph-squares-four',
        subtitle: 'Save a selection of pages as new files.',
      },
      {
        id: 'delete-pages',
        href: import.meta.env.BASE_URL + 'delete-pages.html',
        name: 'Delete Pages',
        icon: 'ph-trash',
        subtitle: 'Remove specific pages from your document.',
      },
      {
        id: 'add-blank-page',
        href: import.meta.env.BASE_URL + 'add-blank-page.html',
        name: 'Add Blank Page',
        icon: 'ph-file-plus',
        subtitle: 'Insert an empty page anywhere in your PDF.',
      },
      {
        id: 'reverse-pages',
        href: import.meta.env.BASE_URL + 'reverse-pages.html',
        name: 'Reverse Pages',
        icon: 'ph-sort-descending',
        subtitle: 'Flip the order of all pages in your document.',
      },
      {
        id: 'rotate-pdf',
        href: import.meta.env.BASE_URL + 'rotate-pdf.html',
        name: 'Rotate PDF',
        icon: 'ph-arrow-clockwise',
        subtitle: 'Turn pages in 90-degree increments.',
      },
      {
        id: 'rotate-custom',
        href: import.meta.env.BASE_URL + 'rotate-custom.html',
        name: 'Rotate by Custom Degrees',
        icon: 'ph-arrows-clockwise',
        subtitle: 'Rotate pages by any custom angle.',
      },
      {
        id: 'n-up-pdf',
        href: import.meta.env.BASE_URL + 'n-up-pdf.html',
        name: 'N-Up PDF',
        icon: 'ph-squares-four',
        subtitle: 'Arrange multiple pages onto a single sheet.',
      },
      {
        id: 'pdf-booklet',
        href: import.meta.env.BASE_URL + 'pdf-booklet.html',
        name: 'PDF Booklet',
        icon: 'ph-book-open',
        subtitle: 'Rearrange pages for double-sided booklet printing.',
      },
      {
        id: 'combine-single-page',
        href: import.meta.env.BASE_URL + 'combine-single-page.html',
        name: 'Combine to Single Page',
        icon: 'ph-arrows-out-line-vertical',
        subtitle: 'Stitch all pages into one continuous scroll.',
      },
      {
        id: 'view-metadata',
        href: import.meta.env.BASE_URL + 'view-metadata.html',
        name: 'View Metadata',
        icon: 'ph-info',
        subtitle: 'Inspect the hidden properties of your PDF.',
      },
      {
        id: 'edit-metadata',
        href: import.meta.env.BASE_URL + 'edit-metadata.html',
        name: 'Edit Metadata',
        icon: 'ph-file-code',
        subtitle: 'Change the author, title, and other properties.',
      },
      {
        id: 'pdf-to-zip',
        href: import.meta.env.BASE_URL + 'pdf-to-zip.html',
        name: 'PDFs to ZIP',
        icon: 'ph-file-zip',
        subtitle: 'Package multiple PDF files into a ZIP archive.',
      },
      {
        id: 'compare-pdfs',
        href: import.meta.env.BASE_URL + 'compare-pdfs.html',
        name: 'Compare PDFs',
        icon: 'ph-git-diff',
        subtitle: 'Compare two PDFs side by side.',
      },
      {
        id: 'posterize-pdf',
        href: import.meta.env.BASE_URL + 'posterize-pdf.html',
        name: 'Posterize PDF',
        icon: 'ph-notepad',
        subtitle: 'Split a large page into multiple smaller pages.',
      },
    ],
  },
  {
    name: 'Optimize & Repair',
    tools: [
      {
        id: 'compress-pdf',
        href: import.meta.env.BASE_URL + 'compress-pdf.html',
        name: 'Compress PDF',
        icon: 'ph-lightning',
        subtitle: 'Reduce the file size of your PDF.',
      },
      {
        id: 'pdf-to-pdfa',
        href: import.meta.env.BASE_URL + 'pdf-to-pdfa.html',
        name: 'PDF to PDF/A',
        icon: 'ph-archive',
        subtitle: 'Convert PDF to PDF/A for long-term archiving.',
      },
      {
        id: 'fix-page-size',
        href: import.meta.env.BASE_URL + 'fix-page-size.html',
        name: 'Fix Page Size',
        icon: 'ph-ruler',
        subtitle: 'Standardize all pages to a uniform size.',
      },
      {
        id: 'linearize-pdf',
        href: import.meta.env.BASE_URL + 'linearize-pdf.html',
        name: 'Linearize PDF',
        icon: 'ph-gauge',
        subtitle: 'Optimize PDF for fast web viewing.',
      },
      {
        id: 'page-dimensions',
        href: import.meta.env.BASE_URL + 'page-dimensions.html',
        name: 'Page Dimensions',
        icon: 'ph-ruler',
        subtitle: 'Analyze page size, orientation, and units.',
      },
      {
        id: 'remove-restrictions',
        href: import.meta.env.BASE_URL + 'remove-restrictions.html',
        name: 'Remove Restrictions',
        icon: 'ph-link-break',
        subtitle:
          'Remove password protection and security restrictions associated with digitally signed PDF files.',
      },
      {
        id: 'repair-pdf',
        href: import.meta.env.BASE_URL + 'repair-pdf.html',
        name: 'Repair PDF',
        icon: 'ph-wrench',
        subtitle: 'Recover data from corrupted or damaged PDF files.',
      },
      {
        id: 'rasterize-pdf',
        href: import.meta.env.BASE_URL + 'rasterize-pdf.html',
        name: 'Rasterize PDF',
        icon: 'ph-image',
        subtitle:
          'Convert PDF to image-based PDF. Flatten layers and remove selectable text.',
      },
    ],
  },
  {
    name: 'Secure PDF',
    tools: [
      {
        id: 'encrypt-pdf',
        href: import.meta.env.BASE_URL + 'encrypt-pdf.html',
        name: 'Encrypt PDF',
        icon: 'ph-lock',
        subtitle: 'Lock your PDF by adding a password.',
      },
      {
        id: 'sanitize-pdf',
        href: import.meta.env.BASE_URL + 'sanitize-pdf.html',
        name: 'Sanitize PDF',
        icon: 'ph-broom',
        subtitle: 'Remove metadata, annotations, scripts, and more.',
      },
      {
        id: 'decrypt-pdf',
        href: import.meta.env.BASE_URL + 'decrypt-pdf.html',
        name: 'Decrypt PDF',
        icon: 'ph-lock-open',
        subtitle: 'Unlock PDF by removing password protection.',
      },
      {
        id: 'flatten-pdf',
        href: import.meta.env.BASE_URL + 'flatten-pdf.html',
        name: 'Flatten PDF',
        icon: 'ph-stack',
        subtitle: 'Make form fields and annotations non-editable.',
      },
      {
        id: 'remove-metadata',
        href: import.meta.env.BASE_URL + 'remove-metadata.html',
        name: 'Remove Metadata',
        icon: 'ph-file-x',
        subtitle: 'Strip hidden data from your PDF.',
      },
      {
        id: 'change-permissions',
        href: import.meta.env.BASE_URL + 'change-permissions.html',
        name: 'Change Permissions',
        icon: 'ph-shield-check',
        subtitle: 'Set or change user permissions on a PDF.',
      },
      {
        id: 'digital-sign-pdf',
        href: import.meta.env.BASE_URL + 'digital-sign-pdf.html',
        name: 'Digital Signature',
        icon: 'ph-certificate',
        subtitle:
          'Add a cryptographic digital signature using X.509 certificates.',
      },
      {
        id: 'validate-signature-pdf',
        href: import.meta.env.BASE_URL + 'validate-signature-pdf.html',
        name: 'Validate Signature',
        icon: 'ph-seal-check',
        subtitle: 'Verify digital signatures and view certificate details.',
      },
    ],
  },
];
